// <auto-generated />
using System;
using EstaparGarage.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstaparGarage.Data.Migrations
{
    [DbContext(typeof(EstaparDbcontext))]
    partial class EstaparDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EstaparGarage.Bussinees.Models.FormaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FormasPagamento", (string)null);
                });

            modelBuilder.Entity("EstaparGarage.Bussinees.Models.Garagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<decimal>("Preco_1aHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Preco_HorasExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Preco_Mensalista")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Garangens", (string)null);
                });

            modelBuilder.Entity("EstaparGarage.Bussinees.Models.Passagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CarroMarca")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("CarroModelo")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("CarroPlaca")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("NomeGaragem")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Passagens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
